spring.application.name=ciclos-transportes-service

# Configuración del servidor (Tu puerto actual)
server.port=8088

# 1. URL de conexión a Neon DB (Asegúrate de cambiar 'nombre_de_tu_bd_aqui' para que no choque con tus colegas)
spring.datasource.url=jdbc:postgresql://ep-wandering-hill-apt6gpev-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require

# 2. Credenciales de acceso
spring.datasource.username=neondb_owner
spring.datasource.password=npg_RJpsfz9bUF7d

# 3. Driver de la base de datos
spring.datasource.driver-class-name=org.postgresql.Driver

# 4. Estrategia de Hibernate (update: crea o modifica tablas automáticamente según tu modelo en Java)
spring.jpa.hibernate.ddl-auto=update

# 5. Muestra en la terminal de VS Code las sentencias SQL reales que se están ejecutando (Espectacular para revisar)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 6. Dialecto específico para comunicarse de forma óptima con Postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect