spring.application.name=ciclos-transportes-service

# Configuración del servidor (Tu puerto actual)
server.port=8088

# 1. URL de conexión a Neon DB (Asegúrate de cambiar 'nombre_de_tu_bd_aqui' para que no choque con tus colegas)
spring.datasource.url={NEON_DB_URL}

# 2. Credenciales de acceso
spring.datasource.username={NEON_DB_USER}
spring.datasource.password={NEON_DB_PASS}

# 3. Driver de la base de datos
spring.datasource.driver-class-name=org.postgresql.Driver

# 4. Estrategia de Hibernate (update: crea o modifica tablas automáticamente según tu modelo en Java)
spring.jpa.hibernate.ddl-auto=update

# 5. Muestra en la terminal de VS Code las sentencias SQL reales que se están ejecutando (Espectacular para revisar)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 6. Dialecto específico para comunicarse de forma óptima con Postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
